### PR TITLE
Update op-geth dependency

### PR DESCRIPTION
**Pull request by karlb**
So this is a pretty simple pr to update the op-geth reference. Unfortunately updating the geth reference broke some stuff so we needed to fix that (fixed here https://github.com/celo-org/op-geth/pull/247) and then I think the tests are just really flaky and I didn't realise so spent some time trying different versions of op-geth but what was really required was just re-running the ci workflow.

Anyway now it seems to be working with an up to date op-geth reference.

### CODE REVIEW

**Comment by karlb** [comment]
Thanks @piersy! Looks good to me, but I can't approve my own PR.

**Comment by piersy** [comment]
> Thanks @piersy! Looks good to me, but I can't approve my own PR.

I'll re-make it and request your review

**Comment by piersy** [comment]
Opening a new pr here #248 so that @karlb can approve

**Comment by karlb** [comment]
Closed in favor of https://github.com/celo-org/optimism/pull/248

**Pull request closed without merging**
